In [ ]:
1. What is the salary for Data Analyst?
Query:
SELECT job_salary FROM job_post WHERE job_position='Data Analyst';

Relational_Algebra:
π job_salary
 σ job_position = "Data Analyst" job_post


    
2. list the companies with ratings greater than 4 ?
Query:
SELECT c.company_name,cr.ratings_overall FROM company_ratings cr inner join company c on cr.company_id = c.id WHERE cr.ratings_overall > 4;

Relational_Algebra:
π c . company_name, cr . ratings_overall
 σ cr . ratings_overall > 4
  (ρ cr company_ratings ⋈ cr . company_id = c . id
   ρ c company)



3. What are the salaries offered in Boston?
Query:
SELECT job_salary FROM job_post WHERE job_location ='Boston'; 

Relational_Algebra:
π job_salary
 σ job_location = "Boston" job_post
    
    
    
4. What is the salary for Data Analyst?
Query:
select job_salary from job_post where job_position='Data analyst';

Relational_Algebra:
π job_salary
 σ job_position = "Data analyst" job_post

    
    
5. Which is the least paying job in California?
Query:
select MIN(job_salary) from job_post where job_location='California';

Relational_Algebra:
π MIN (job_salary)
 γ MIN (job_salary)
  σ job_location = "California" job_post



6. select company with most job posting
Query:
select company_name, count(company_id) from company c inner join job_post jp on c.id = jp.company_id 
group by company_name order by count(company_id) desc limit 1;

Relational_Algebra:
τ COUNT (company_id) ↓
 γ company_name, COUNT (company_id)
  (ρ c company ⋈ c . id = jp . company_id
   ρ jp job_post)



7.Get a list of all the internships
Query:
select * from job_post where job_position like '%internship%';

Relational_Algebra:
σ job_position LIKE "%internship%" job_post



8.Get the avg salary of a data analyst role.
Query:
select avg(job_salary) from job_post where job_position='Data analyst';

Relational_Algebra:
π AVG (job_salary)
 γ AVG (job_salary)
  σ job_position = "Data analyst" job_post



9. How is the management of a company rated for netflix?
Query:
select c.company_name,cr.rating_management from company_ratings cr inner join company c on cr.company_id = c.id 
where c.company_name = "Netflix";

Relational_Algebra:
π c . company_name, cr . rating_management
 σ c . company_name = "Netflix"
  (ρ cr company_ratings ⋈ cr . company_id = c . id
   ρ c company)



10.which companies are offering financial analyst jobs
Query:
select c.company_name, jp.job_position from company c inner join job_post jp on c.id=jp.company_id 
where job_position like '%Financial Analyst%';

Relational_Algebra:
π c . company_name, jp . job_position
 σ job_position LIKE "%Financial Analyst%"
  (ρ c company ⋈ c . id = jp . company_id
   ρ jp job_post)



11. select the company with most followers
Query:
select distinct twitter_handle_name,followers_count from company_twitter_profile pf order by followers_count desc limit 1;

Relational_Algebra:
δ
 τ followers_count ↓
  π twitter_handle_name, followers_count
   ρ pf company_twitter_profile
    
    
    
12. select the company with most likes in tweets
Query:
select twt.twitter_handle_id, twitter_handle_name, tweet_favorite_count from company_tweets_info twt 
inner join company_twitter_profile pf on twt.twitter_handle_id = pf.twitter_handle_id
order by tweet_favorite_count desc limit 1;

Relational_Algebra:
τ tweet_favorite_count ↓
 π twt . twitter_handle_id, twitter_handle_name, tweet_favorite_count
  (ρ twt company_tweets_info ⋈ twt . twitter_handle_id = pf . twitter_handle_id
   ρ pf company_twitter_profile)



13. The company which is more ative in twitter?
Query:
select Distinct twt.twitter_handle_id , pf.twitter_handle_name, count(tweet_id) as tweet_count from 
company_tweets_info twt inner join company_twitter_profile pf on twt.twitter_handle_id = pf.twitter_handle_id 
group by twitter_handle_id, twitter_handle_name order by tweet_count desc limit 1;

Relational_Algebra:
    δ
 τ tweet_count ↓
  π twt . twitter_handle_id, pf . twitter_handle_name, COUNT (tweet_id) → tweet_count
   γ twitter_handle_id, twitter_handle_name, COUNT (tweet_id)
    (ρ twt company_tweets_info ⋈ twt . twitter_handle_id = pf . twitter_handle_id
     ρ pf company_twitter_profile)

    
    
14. is the company verified in twitter or not?
Query:
select verified from company_twitter_profile 
where twitter_handle_name = 'FidelityJobs';

Relational_Algebra:
π verified
 σ twitter_handle_name = "FidelityJobs" company_twitter_profile
    
    
    
15. get the company twitter profile name for fidelity
Query:
select pf.twitter_handle_name,c.company_name from company_twitter_profile pf inner join 
company c on pf.twitter_handle_name=c.twitter_handle_name
where c.company_name = 'Fidelity';

Relational_Algebra:
π pf . twitter_handle_name, c . company_name
 σ c . company_name = "Fidelity"
  (ρ pf company_twitter_profile ⋈ pf . twitter_handle_name = c . twitter_handle_name
   ρ c company)



16. list top 3 companies according to popular hashtags
Query:
select hashtags, count(hashtags), twitter_handle_name as popularity_count
from company_tweet_hashtags ht 
inner join company_tweets_info twt on ht.tweet_id = twt.tweet_id
inner join company_twitter_profile pf on twt.twitter_handle_id = pf.twitter_handle_id
group by hashtags, twitter_handle_name
order by count(hashtags) desc limit 3;

Relational_Algebra:
τ COUNT (hashtags) ↓
 π hashtags, COUNT (hashtags), twitter_handle_name → popularity_count
  γ hashtags, twitter_handle_name, COUNT (hashtags)
   (ρ ht company_tweet_hashtags ⋈ ht . tweet_id = twt . tweet_id
    ρ twt company_tweets_info ⋈ twt . twitter_handle_id = pf . twitter_handle_id
     ρ pf company_twitter_profile)
    
    
    
17.Does the company provide medical insurance for a particular job?
Query:
select b.medical_insurance from benefits_offered b inner join job_post j on b.job_post_id = j.id where b.medical_insurance = 1;

Relational_Algebra:
π b . medical_insurance
 σ b . medical_insurance = 1
  (ρ b benefits_offered ⋈ b . job_post_id = j . id
   ρ j job_post)



18.Does the company sponsor international applicants?
Query:
select b.international_applicant from benefits_offered b inner join job_post j on b.job_post_id = j.id where b.international_applicants = 1;

Relational_Algebra:
π b . international_applicant
 σ b . international_applicants = 1
  (ρ b benefits_offered ⋈ b . job_post_id = j . id
   ρ j job_post)



19.List all the details for Remote data analyst roles.
Query:
select * from job_post where job_description = 'data analyst' and job_type = 'remote';

Relational_Algebra:
σ job_description = "data analyst" AND job_type = "remote" job_post



20.Review of a particular role for a particular company
Query:
select review from company_review inner join company c on company_review.company_id = c.id
Where employee_title  = 'business analyst' and company_name = 'amazon';

Relational_Algebra:
π review
 σ employee_title = "business analyst" AND company_name = "amazon" (company_review ⋈ company_review . company_id = c . id
  ρ c company)